FROM node:8.12.0-stretch

# Install dependencies
RUN apt-get update && apt-get install -y \
  pdftk \
  fontconfig \
  ghostscript \
  && rm -rf /var/lib/apt/lists/*

# Install postgres
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
  && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' \
  && apt-get update && apt-get install -y postgresql-client-10 \
  && rm -rf /var/lib/apt/lists/*
