#!/usr/bin/env bash

CWD=`pwd`
ENV=${NODE_ENV:-development}

# copy badges for default campaigns
if [ ! -d "$CWD/public/uploads/${ENV}/badges/" ]
  then
    mkdir -p "$CWD/public/uploads/${ENV}/badges/"
fi

cp -r ./public/images/badges/* "$CWD/public/uploads/${ENV}/badges/"
find "$CWD/public/uploads/${ENV}/badges"
