#!/usr/bin/env sh

RED='\033[0;31m'
GREEN='\033[1;32m'
NC='\033[0m'

psqlInstalled=$(which psql)

if [ "$psqlInstalled" != "psql not found" ]
then
  if [ "$NODE_ENV" = "test" ]
  then
    echo "${GREEN}Resetting test database${NC}"
    env PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST:-localhost} -U ${DB_USER:-$(whoami)} -c 'DROP DATABASE IF EXISTS "dispute_tools_test"'

    env PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST:-localhost} -U ${DB_USER:-$(whoami)} -c 'CREATE DATABASE "dispute_tools_test"'
  else
    echo "${GREEN}Resetting development database${NC}"
    env PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST:-localhost} -U ${DB_USER:-$(whoami)} -c 'DROP DATABASE IF EXISTS "dispute_tools_development"'

    env PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST:-localhost} -U ${DB_USER:-$(whoami)} -c 'CREATE DATABASE "dispute_tools_development"'
  fi
  exit 0
else
  echo "${RED}Please install psql${NC}"
  exit 1
fi
