#!/usr/bin/env sh

psql -h ${POSTGRES_HOST:-localhost} -U ${POSTGRES_USER:-$(whoami)} -c 'DROP DATABASE IF EXISTS "debtcollective_test"'

psql -h ${POSTGRES_HOST:-localhost} -U ${POSTGRES_USER:-$(whoami)} -c 'CREATE DATABASE "debtcollective_test"'

psql -h ${POSTGRES_HOST:-localhost} -U ${POSTGRES_USER:-$(whoami)} -c 'DROP DATABASE IF EXISTS "debtcollective_development"'

psql -h ${POSTGRES_HOST:-localhost} -U ${POSTGRES_USER:-$(whoami)} -c 'CREATE DATABASE "debtcollective_development"'
