module.exports = {
  alphaDash: require('./alphaDash'),
  checkbox: require('./checkbox'),
  currency: require('./currency'),
  date: require('./date'),
  email: require('./email'),
  maxLength: require('./maxLength'),
  minLength: require('./minLength'),
  number: require('./number'),
  oneOf: require('./oneOf'),
  phone: require('./phone'),
  required: require('./required'),
  ssn: require('./ssn'),
  text: require('./text'),
  usStates: require('./usStates'),
  yesnoRadio: require('./yesnoRadio'),
  zip: require('./zip'),
};
