#!/usr/bin/env sh

ENV=${1:-production}

echo 'Build running with' ${ENV} 'environment'
echo 'Add one option value to this command to change environment'

export NODE_ENV=ENV
npx rimraf public/build

yarn svg
webpack -p --config webpack.config.js
