#!/usr/bin/env bash

ENV=$1

# Install awscli
sudo apt-get update
sudo apt-get install python-dev
curl -O https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
echo 'export PATH=~/.local/bin:$PATH' >> ~/.bash_profile
source ~/.bash_profile
pip install awscli --upgrade --user

eval $(aws ecr get-login --no-include-email --region=us-west-1)
docker build -t dispute-tools-$ENV .
docker tag dispute-tools-$ENV:latest "$CONTAINER_REGISTRY-$ENV:latest"
docker push "$DOCKER_REGISTRY-$ENV:latest"
