#!/usr/bin/env bash

ENV=$1

# Install awscli
sudo apt-get update
sudo apt-get install python-dev
curl -O https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
echo 'export PATH=~/.local/bin:$PATH' >> ~/.bash_profile
source ~/.bash_profile
pip install awscli --upgrade --user

docker build -t dispute-tools-development .

eval "$(aws ecr get-login --no-include-email --region us-west-1 --registry-ids 183550513269)"
docker tag dispute-tools-development:latest 183550513269.dkr.ecr.us-west-1.amazonaws.com/dispute-tools-development:latest
docker push 183550513269.dkr.ecr.us-west-1.amazonaws.com/dispute-tools-development:latest
