#!/usr/bin/env bash
pip install awscli --upgrade --user
$(aws ecr get-login --no-include-email --region=us-west-2)
docker build -t tdc-dispute-tools .
docker tag tdc-dispute-tools:latest $DOCKER_REGISTRY/tdc-dispute-tools:latest
docker push $DOCKER_REGISTRY/tdc-dispute-tools:latest
