#!/usr/bin/env bash

ENV=$1

sudo apt-get install awscli
eval $(aws ecr get-login --no-include-email --region=us-west-2)
docker build -t tdc-dispute-tools .
docker tag tdc-dispute-tools:latest $DOCKER_REGISTRY/ds-dispute-tools-$ENV:latest
docker push $DOCKER_REGISTRY/ds-dispute-tools-$ENV:latest
