#!/usr/bin/env sh

echo "Installing apt testing repositories"
echo 'APT::Default-Release "stable";' >> /etc/apt/apt.conf.d/99defaultrelease
echo -e "deb     http://ftp.de.debian.org/debian/    stable main contrib non-free \n\
deb-src http://ftp.de.debian.org/debian/    stable main contrib non-free \n\
\n\
deb     http://security.debian.org/         stable/updates  main contrib non-free" >> /etc/apt/sources.list.d/stable.list

echo -e "deb     http://ftp.de.debian.org/debian/    testing main contrib non-free \n\
deb-src http://ftp.de.debian.org/debian/    testing main contrib non-free \n\
\n\
deb     http://security.debian.org/         testing/updates  main contrib non-free" >> /etc/apt/sources.list.d/testing.list

echo "updating"
apt-get update

echo "installing"
apt-get -t testing install ghostscript
