#!/usr/bin/env sh

echo "Installing apt testing repositories"
echo 'APT::Default-Release "stable";' >> /etc/apt/apt.conf.d/99defaultrelease
cat <<EOT >> /etc/apt/sources.list.d/stable.list
deb     http://ftp.de.debian.org/debian/    stable main contrib non-free
deb-src http://ftp.de.debian.org/debian/    stable main contrib non-free

deb     http://security.debian.org/         stable/updates  main contrib non-free
EOT

cat<<EOT >> /etc/apt/sources.list.d/testing.list
deb     http://ftp.de.debian.org/debian/    testing main contrib non-free
deb-src http://ftp.de.debian.org/debian/    testing main contrib non-free

deb     http://security.debian.org/         testing/updates  main contrib non-free
EOT


echo "updating"
apt-get update

echo "installing"
apt-get -t testing install ghostscript
