#!/usr/bin/env sh

files=$(
  git diff --name-only origin/master | \
    grep '\.js$'
)

if [ "x$files" != "x" ]; then
  # Wrap in parnes so it handles the line-breaks from git diff w/o complaining
  (./node_modules/.bin/eslint --fix $files)
fi

files=$(
  git diff --name-only origin/master | \
    grep '\.vue$'
)

if [ "x$files" != "x" ]; then
  # Wrap in parnes so it handles the line-breaks from git diff w/o complaining
  (./node_modules/.bin/eslint --fix $files)
fi

exit 0;
