#!/usr/bin/env sh

export NODE_ENV=staging

set -e

npm install --silent
cp ./../shared/knexfile.js ./
cp ./../shared/config.js ./config/
knex migrate:latest
rm build/index.json
npm run build
pm2 startOrRestart ecosystem.json --env staging
