#!/usr/bin/env bash

export NODE_ENV=staging

set -e

source ~/.profile
npm install --silent
cp ./../shared/knexfile.js ./
cp ./../shared/config.js ./config/
ln -s /home/deploy/apps/tdc/shared/uploads /home/deploy/apps/tdc/current/public/
knex migrate:latest
rm -f build/index.json
npm run build
pm2 startOrRestart ecosystem.json --env staging
