#!/usr/bin/env bash

export NODE_ENV=production

set -e

. ~/.nvm/nvm.sh

nvm use v6
npm i

cp ./../shared/knexfile.js ./
cp ./../shared/config.js ./config/
ln -sf /home/deploy/apps/tdc/shared/uploads /home/deploy/apps/tdc/current/public/

npm i -g knex pm2 svg-sprite
knex migrate:latest
knex seed:run

rm -f build/index.json
npm run build

pm2 startOrRestart ecosystem.json --env production
