#!/usr/bin/env bash

. ~/.nvm/nvm.sh

nvm use v6
yarn

cp ./../shared/knexfile.js ./
cp ./../shared/config.js ./config/
ln -sf /home/deploy/apps/tdc/shared/uploads /home/deploy/apps/tdc/current/public/

yarn db:migrate -- --env production
yarn build

pm2 startOrRestart ecosystem.json --env production
