#!/usr/bin/env bash

export NODE_ENV=staging

set -e

source ~/.profile
ssh-keyscan -H '54.160.57.68' >> $HOME/.ssh/known_hosts
npm install --silent
cp ./../shared/knexfile.js ./
cp ./../shared/config.js ./config/
knex migrate:latest
rm -f build/index.json
npm run build
pm2 startOrRestart ecosystem.json --env staging
