#!/usr/bin/env node

process.env.HEADLESS = 1;

require('../../lib/core');

/* global User, Dispute, DisputeStatus, DisputeMailer */

Dispute.query()
.then(results => {
  Promise.all(
    results.map(dispute => {
      const ds = new DisputeStatus({
        comment: 'Sending automatically from AI',
        disputeId: dispute.id,
        status: 'User Update',
      });

      return User.query()
      .where({
        id: dispute.user_id,
      }).then(([user]) => {
        console.log('> Sending dispute from', user.email, 'to admin');

        return DisputeMailer.sendToAdmins({
          user,
          dispute,
          disputeStatus: ds,
        });
      });
    })
  ).then(() => {
    console.log('OK');
    process.exit();
  });
})
.catch(error => {
  console.log(error);
  process.exit(1);
});
