#!/usr/bin/env sh

export NODE_ENV=test
export PORT=9090
export DISCOURSE_NODE_SUPPRESS_LOGS=1

yarn utils:resetdb
yarn utils:knexreset

yarn nyc --reporter=lcov --report-dir coverage/unit node tests/unit.js "$1"
